version: '3'
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
    ports:
      - "80:80"
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/app
      - ./docker:/usr/local/etc/php/conf.d
    depends_on:
      - mysql
      - redis
  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: music_app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    ports:
      - "33061:3306"
  node:
    image: node:12.6-alpine
    volumes:
      - ./:/app
    working_dir: /app
  redis:
    image: redis:5-alpine
    volumes:
      - redis:/data

volumes:
  mysql:
  redis:
  composer:
